---

- name: download vivtoriametrics archives
  include_tasks: download/main.yml
  loop:
    "{{ victoriametrics_release.files }}"
  loop_control:
    index_var: index
    loop_var: download_file
    label: "file: {{ download_file }}"
  when:
    - victoriametrics_release.files is defined
    - victoriametrics_release.files | count > 0

# - block:
#     - name: get checksum list
#       set_fact:
#         # https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.76.1/victoria-metrics-amd64-v1.76.1_checksums.txt
#         __victoriametrics_checksums: "{{
#           lookup('url',
#                  victoriametrics_release.download_url + '/download/v' + victoriametrics_version + '/victoria-metrics-' + go_arch + '-v' + victoriametrics_version + '_checksums.txt',
#                  wantlist=True) | list
#           }}"
#       run_once: true
#
#     - name: d
#       debug:
#         msg: "{{ __victoriametrics_checksums }}"
#
#     - name: get checksum for {{ go_arch }} architecture
#       set_fact:
#         __victoriametrics_checksum: "{{ __victoriametrics_checksums | victoriametrics_checksum('linux', go_arch) }}"
#   delegate_to: localhost
#
# - name: download victoriametrics binary archive
#   become: false
#   delegate_to: "{{ victoriametrics_delegate_to }}"
#   get_url:
#     url: "{{ victoriametrics_release.download_url }}/download/v{{ victoriametrics_version }}/{{ victoriametrics_release.file }}"
#     dest: "{{ victoriametrics_local_tmp_directory }}/{{ victoriametrics_release.file }}"
#     checksum: "sha256:{{ __victoriametrics_checksum }}"
#   register: _download_archive
#   until: _download_archive is succeeded
#   retries: 5
#   delay: 2
#   check_mode: false
#
# - name: download vmutils archive
#   become: false
#   delegate_to: "{{ victoriametrics_delegate_to }}"
#   get_url:
#     url: "{{ victoriametrics_release.download_url }}/download/v{{ victoriametrics_version }}/{{ victoriametrics_release.file }}"
#     dest: "{{ victoriametrics_local_tmp_directory }}/{{ victoriametrics_release.file }}"
#     checksum: "sha256:{{ __victoriametrics_checksum }}"
#   register: _download_archive
#   until: _download_archive is succeeded
#   retries: 5
#   delay: 2
#   check_mode: false
#
# https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.76.1/vmutils-amd64-v1.76.1.tar.gz
#
#
# - name: extract victoriametrics archive
#   become: false
#   delegate_to: "{{ victoriametrics_delegate_to }}"
#   unarchive:
#     src: "{{ victoriametrics_local_tmp_directory }}/{{ victoriametrics_release.file }}"
#     dest: "{{ victoriametrics_local_tmp_directory }}/"
#     copy: false

...
